"""empty message

Revision ID: 54dd2c75b11f
Revises: c17de15f9bb2
Create Date: 2022-09-14 03:12:07.086278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dd2c75b11f'
down_revision = 'c17de15f9bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apitoken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    # ### end Alembic commands ###
